## Autograd: automatic differentiation

`autograd` 是 Pytorch 中对于所有神经网络来说非常重要的库，这个库提供了对 Tensors 的所有操作的自动微分操作。

### Tensor

In [1]:
import torch

创建一个 tensor， 并让 `requires_grad=True`

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


对 tensor 进行任意一个操作

In [4]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


`y` 是一个操作的结果，所以它带有操作 `grad_fn` 

In [5]:
print(y.grad_fn)

In [7]:
z = y * y * 3
out = z.mean()

print('z=', z)
print('out=', out)

z= tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>)
out= tensor(27., grad_fn=<MeanBackward1>)


In [8]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


### Gradients

In [9]:
out.backward()

输出 d(out)/dx, out=z.mean(), z= y\*y\*3, y=x+2

In [10]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [11]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 237.5009, 1774.2396,  274.0625], grad_fn=<MulBackward>)


In [12]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([ 102.4000, 1024.0000,    0.1024])


In [13]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
